Iter9
egosha7/shortlink pull request #13
Opened 2023-06-05 12:10 UTC by egosha7

2023-06-06 10:28 UTC, maxlyaptsev requested changes

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	if r.Method != "POST" {
это задача роутера

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		if r.Header.Get("Content-Encoding") == "gzip" {
работа со сжатием должна быть вынесена отдельно, в middleware

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func (s *URLStore) LoadFromFile() error {
LoadFromFile не является хэндлером, почему он здесь?

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func (s *URLStore) SaveToFile() error {
не хэндлер

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	if r.Header.Get("Content-Encoding") == "gzip" {
аналогично, должно быть в мидлваре

2023-06-06 10:28 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	r.HandleFunc(
роутинг лучше вынести в основную логику сервиса

2023-06-06 10:28 UTC, maxlyaptsev commented on cmd/shortener/tmp/some.json
> +[{"ID":"def456","URL":"https://google.com"},{"ID":"uEBMGt","URL":"https://example.com"}]
tmp не должно быть в репозитории. Такие структуры могут быть в тестах, даже для ручного тестирования - фикстуры и прочее. Но tmp предполагает что это просто временные файлы

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/config/config.go
> +	if os.Getenv("SERVER_ADDRESS") != "" {
если использовать стороннюю библиотеку код сократится до одной строки - env.Parse()

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		initialData := []byte("[{\"ID\":\"def456\",\"URL\":\"https://google.com\"}]")
это нормально для теста, но точно не для рабочих ручек - захардкоженных данных там быть не должно

2023-06-06 10:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		body, err := io.ReadAll(gzipReader)
можно срезу декодировать без чтения в переменню (json.Decode)

2023-06-07 23:17 UTC, egosha7 commented
Привет! Инкременты 1 спринта смерджил в мэйн. Все твои комментарии увидел и внес изменения, кроме обработки сжатия, если ничего не путаю, то это у меня функции GzipMiddleware

2023-06-08 16:07 UTC, maxlyaptsev requested changes

2023-06-08 16:07 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	if r.Method != "POST" {
актуально

2023-06-08 16:07 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	if r.Header.Get("Content-Encoding") == "gzip" {
актуально

2023-06-08 16:07 UTC, maxlyaptsev commented on internal/storage/storage.go
> +	}
```suggestion
	if fileInfo.Size() == 0 {
                 return nil
        {
	if err = json.NewDecoder(file).Decode(&s.urls); err != nil {
		return err
	}
```
можно короче, логика не меняется

2023-06-09 23:11 UTC, egosha7 commented
Исправил. Прошу прощение за задержку, нам в Адлере отключают интернет без предупреждения из-за проведение международного форума и приезда президента в наш город, ничего не мог поделать

2023-06-10 09:47 UTC, maxlyaptsev requested changes

2023-06-10 09:47 UTC, maxlyaptsev commented on internal/config/config.go
> +	addr := flag.String("a", defaultValue.Addr, "HTTP-адрес сервера")
```suggestion
        config := Config{}
	flag.StringVar(&config.Addr, "a", defaultValue.Addr, "HTTP-адрес сервера")
```
тут тоже можно сразу в структуру записывать значения

2023-06-10 09:47 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	if uncompressedBody := r.Context().Value(Key("uncompressedBody")); uncompressedBody != nil {
не должно быть в ручке два варианта реализации. Мидлвара по сжатию должна разжимать данные самостоятельно при необходимости, а в ручку поступят всегда уже подготовленные разжатые данные

В этом и суть мидлвары, что все происходит в прослойке незаметно и независимо от ручек, как это сделано для логирования. 
В курсе есть пример для навыков алисы, его можно практически полностью скопировать

2023-06-10 09:47 UTC, maxlyaptsev commented on internal/services/services.go
> +package services
нужно дать файлу более понятное название

2023-06-11 09:45 UTC, egosha7 commented
Прости что сразу не понял твои замечания, теперь ручки остались без изменений и получают тело запроса из *http.Request без зависимости имеется сжатие или нет, мидлвару саму отправил в отдельный пакет. Другие замечания тоже отработал

2023-06-12 08:55 UTC, maxlyaptsev approved these changes

2023-06-12 08:55 UTC, maxlyaptsev commented on internal/compress/compress.go
> +				r.Header.Del("Content-Length")
зачем удалять хедеры?

2023-06-12 08:55 UTC, maxlyaptsev commented on internal/compress/compress.go
> +				r.Body = http.MaxBytesReader(w, gz, r.ContentLength)
мы не должны менять тело запроса. Мы должны заменить writer и reader - почитай еще раз раздел в курсе, там хороший пример с алисой. Нужно реализовать интерфейсы ридера и райтера, и просто их подменить если пришли сжатые данные.

2023-06-14 12:04 UTC, merged