Iter13
egosha7/shortlink pull request #17
Opened 2023-06-18 20:17 UTC by egosha7

2023-06-20 22:07 UTC, maxlyaptsev requested changes

2023-06-20 22:07 UTC, maxlyaptsev commented on internal/handlers/handlers_DB.go
> +			return
над циклом хорошо бы добавить транзакцию - либо все сохранили, либо ничего. Сейчас на какой-то записи вернем ошибку, но все что было до этого сохранится в бд

2023-06-20 22:07 UTC, maxlyaptsev commented on internal/handlers/handlers_DB.go
> +func ShortenURLuseDB(w http.ResponseWriter, r *http.Request, cfg *config.Config, repo storage.URLRepository) {
лучше не прокидывать прям все конфиги, а только те что будут использоваться, так и тест потом легче писать

2023-06-21 10:58 UTC, egosha7 commented on internal/router/router.go
> +	if conn != nil {
Изменил реализацию, под твой ответ

2023-06-21 11:03 UTC, egosha7 commented on internal/storage/storage.go
> +	if err != nil {
Поменял пару условий на свитч, хотя с тобой согласен, выглядело громоздко

2023-06-21 11:28 UTC, egosha7 commented on internal/storage/storage.go
> +		if pgErr, ok := err.(*pgconn.PgError); ok && pgErr.Code == "23505" {
Поменял 23505 на pgerrcode.UniqueViolation

2023-06-21 12:03 UTC, egosha7 commented on internal/router/router.go
> +						err := conn.Ping(context.Background())
Именно поэтому и решил так сделать) Переместил в пакет db

2023-06-21 12:07 UTC, egosha7 commented on internal/handlers/handlers_DB.go
> +	repo.PrintAllURLs()
Вывод из бд делал на один раз, что бы ошибку заметить, но забыл удалить. Пакет удалил

2023-06-21 12:18 UTC, egosha7 commented on internal/storage/storage.go
> +				return r.AddURL(newID, url)
Согласен. Поменял логику, при вызове функции AddURL вызывается  addURLWithRetry, где вместе с привычными данными передается ещё и количество повторов генерации нового айди, при достижении максимума выдается соответствующая ошибка

2023-06-21 16:00 UTC, egosha7 commented on internal/handlers/handlers_DB.go
> +			return
Добавил функции в сторедж, которые используют одну транзакцию для записи в БД

2023-06-21 16:13 UTC, egosha7 commented on internal/handlers/handlers_DB.go
> +func ShortenURLuseDB(w http.ResponseWriter, r *http.Request, cfg *config.Config, repo storage.URLRepository) {
Done!

2023-06-27 20:52 UTC, merged