Iter15
egosha7/shortlink pull request #19
Opened 2023-06-28 11:29 UTC by egosha7

2023-06-28 17:28 UTC, maxlyaptsev requested changes

2023-06-28 17:28 UTC, maxlyaptsev commented on internal/handlers/auth.go
> +package handlers
авторизация это все же не handler - давай вынесем в пакет с мидлварами или с авторизацией

2023-06-28 17:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		urlsChan <- url
тут мы разделяем ссылки, чем наоборот усложняем жизнь. Суть задания объединить поток запросов из ручек в один канал, который будет читать один воркер и последовательно выполнять запросы по мере своей возможности


например: 
```go
//  в ручке можно вызвать такой метод
worer.DeleteUrls()
```

```go
// который запишет все данные в канал
func (w *worker) DeleteUrls(urls Urls) {
worker <- urls
}

// запускаем асинхронный воркер
go work()

// который читает канал и удаляет url
func (w *worker) work() {
// используем сторенж конечно же, не напрямую -  у всего своя зона ответственности
}
```

2023-06-28 17:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	go func() {
1 - не стоит держать всю логику работы в хэндлере. Принцип единой ответственности - давай просто вызовем метод для сохранения данных, который положит данные в канал и вернем 200 ОК

2 - так мы не сможем контролировать горутину, их количество и завершение. Может быть и утечка и не заметим т.к. хэндлер уже отработал, а горутина где-то в фоне висит

2023-06-28 17:28 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		if userID == "" {
```suggestion
	} else if userID == "" {
```

2023-06-30 14:27 UTC, egosha7 commented on internal/handlers/handlers.go
> +		if userID == "" {
Исправил

2023-06-30 14:31 UTC, egosha7 commented on internal/handlers/handlers.go
> +		urlsChan <- url
Краткое описание того, что было сделано:

Создан экземпляр воркера (wkr := worker.NewWorker(store)) при установке роутера.
В хэндлере DeleteUserURLsHandler передан экземпляр воркера в качестве аргумента.
Внутри хэндлера вызван метод wkr.DeleteURLs(urls, userID) для отправки ссылок и userID в канал воркера.
Добавлен воркер в канале воркеров и изменена функция work, чтобы она читала из этого канала и выполняла удаление ссылок асинхронно.
Возвращен статус HTTP 202 Accepted из хэндлера после отправки ссылок в канал.

2023-06-30 14:42 UTC, egosha7 commented on internal/handlers/handlers.go
> +	go func() {
1 - поправил

2 - не совсем понимаю как это реализовать. В измененном коде горутины открываются при вызове функции DeleteURLs в сторедже, если происходят ошибки, то они будут в логах. А так по заданию хэндлер возвращает 202 Accepted и фактический результат удаления может происходить позже — оповещать пользователя об успешности или неуспешности не нужно

2023-07-02 19:45 UTC, maxlyaptsev commented on internal/storage/storage.go
> +		for _, url := range urls {
в идеале не разделять на отдельные запросы, а сделать одним

2023-07-02 19:47 UTC, maxlyaptsev commented on internal/storage/storage.go
> +	go func() {
горутина здесь лишняя - воркер уже работает в горутине, его ответственность делать запросы асинхронными. Сам же репозиторий может быть обычным

2023-07-03 20:44 UTC, egosha7 commented on internal/storage/storage.go
> +	go func() {
Сделал синхронным. Делал в спешке, поэтому теорию еще буду повторять более тщательно) @maxlyaptsev

2023-07-03 21:02 UTC, egosha7 commented on internal/storage/storage.go
> +		for _, url := range urls {
Да, разбивка ссылок для отправки их отдельными запросами звучит нелогично. Изначально хотел их отправлять одним запросом для каждого json, но перечитав задание решил что вдруг автотесты не пройдут. Тоже переделал

2023-10-25 13:32 UTC, merged