Iter5
egosha7/shortlink pull request #5
Opened 2023-05-12 22:25 UTC by egosha7

2023-05-12 23:44 UTC, egosha7 commented
Автотест по первому инкременту не пройден с ошибкой "Процесс завершен с кодом 1", что означает что произошла паника, но у меня никакой паники и программа работает исправно. Не понимаю с чем связанно.

2023-05-15 07:48 UTC, maxlyaptsev requested changes

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +			io.WriteString(res, form)
эту страницу не нужно выводить, и html там не нужен

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
>  package main
Проект следует разделить на пакеты, как описано в уроке "структура проекта" в начале спринта

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +var config Config
в проекте не должны использоваться глобальные переменные

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +				res.Write([]byte("404"))
для ошибки в http пакете есть специальный метод

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +			fullink := linkey[req.URL.Path[1:]]
chi позволяет получать параметры запроса

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	if addr := os.Getenv("SERVER_ADDRESS"); addr != "" {
с помощью стороннего пакета можно сократить конфигурации по переменным окружения до одной строчки

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	if req.Method != http.MethodPost {
роутер chi позволяет конфигурировать роуты с учетом http метода, рекомендую перечитать урок с описанием сторонних роутеров

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main_test.go
> +func TestMainPageGet(t *testing.T) {
Основной метод написания тестов - это тестовые таблицы, они легче читаются и позволяют добавлять большое количество тест-кейсов

https://github.com/sau00/uber-go-guide-ru/blob/master/style.md#test-tables

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +const form = `<html>
не нужно передавать html, это не ответственность бекенд приложений, да и в задании такого нет

2023-05-15 07:48 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +		linkey[struna] = link
что если по этому адресу уже лежит другая ссылка?

2023-05-19 10:20 UTC, maxlyaptsev requested changes

2023-05-19 10:20 UTC, maxlyaptsev commented on cmd/shortener/main_test.go
> +	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
по заданию необходимо использовать text/plain

2023-05-19 10:20 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func RandStringRunes(n int) string {
пакет должен содержать только только код с определенной ответственностью. Пакет называется handlers, ожидается что тут будут только ручки. `RandStringRunes` - это экспортируемая функция, которая может быть использована в любой части кода. Непраавильно было бы держать ее в этом пакете, лучше вынести в отдельный. И хорошо бы подумать над названием - оно должно быть лаконичным, коротким. Например Runes - это часть внутренней логики, которая не интересна коду, который будет использовать эту функцию.

2023-05-19 10:20 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +var letterRunes = []rune(_const.Runestring)
использование глобальных переменных нежелательно

2023-05-19 10:20 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +			http.Redirect(res, req, fullink, http.StatusSeeOther)
неверный код редиректа

2023-05-20 03:30 UTC, closed without merging